# Generated by Django 4.1.5 on 2023-01-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='')),
                ('daraja', models.CharField(choices=[("Boshlang'ich", "boshlang'ich"), ("o'rta", "O'rta"), ('Yuqori', 'yuqori')], max_length=30)),
                ('narx', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=60)),
                ('sana', models.DateField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('tel', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('malumot', models.CharField(max_length=400)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(default='Yangi', max_length=20)),
                ('sana', models.DateTimeField(blank=True, null=True)),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
                ('profil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz_Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
                ('ustoz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ustoz')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
                ('profil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.PositiveSmallIntegerField(default=5)),
                ('sana', models.DateTimeField(blank=True, null=True)),
                ('matn', models.CharField(max_length=90)),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
                ('profil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.profil')),
            ],
        ),
    ]
